### ISSUE TITLE
Doc suggestion: no ImageMagick on ElCapitan and Sierra

### ISSUE THREAD

**Issue by rebcabin** [mkrphys/ipython-tikzmagic#15]
Suggest you might note in your README.md that ImageMagick does not work (by their own admission) on the two latest releases of the Mac OS, meaning that parts of tikzmagic that depend on ImageMagick will not work on those OSs. Might save some people some time.

**EDIT**

I just discovered that 

    %%tikz -f svg --size 300,400
    \draw (0,0) rectangle (1,1);

works on El Capitan, so if you use `pdf2svg` through the `-f` option, then you can have tikzmagic on ElCapitan. I don't see a way to access the one-liner magic, as in 

    %tikz \draw (0,0) rectangle (1,1);

**Comment by johntfoster** [comment]
I have no issues running tikzmagic with Homebrew installed imagemagick in Sierra.

**Comment by ghost** [comment]
I have ImageMagick installed under El Capitan via MacPorts and it works splendidly well.
