### ISSUE TITLE
"No image generated."

### ISSUE THREAD

**Issue by tnightengale** [mkrphys/ipython-tikzmagic#18]
Hi,

I cannot seem to get tikz to work in Jupyter using your extension. I apologize in advance as I am relatively inexperienced using any kind of Jupyter add on. 

The I run the command`%load_ext tikzmagic` followed by `%tikz \draw (0,0) rectangle (1,1);` in two cells in a Jupyter notebook and receive the error "No image generated".

I saw this previous issue and had been resolved and followed the instructions in that solution, but to no avail. 

I am using jupyter with anaconda (I launch a notebook from terminal using `$ jupyter notebook`). I also have used homebrew to install ImageMagick and pdf2svg. I copied the command line given to install this package using pip. I also believe I used pip to install an older version of tikzmagic from a different repo (if that somehow has any bearing on the issue). 

Any suggestions would be truly welcome. Thanks

**Comment by mahmutkocak** [comment]
I have the same issue.

**Comment by AegeusZerium** [comment]
Did you find any solution ?

**Comment by irustandi** [comment]
On Ubuntu 18.04, I ran into the same issue. It seems the problem was because ImageMagick tightened their security policy so that it prevented the generation of PNG file from the PDF file generated by latex. To fix this problem, I edited /etc/ImageMagick-6/policy.xml, changing the following

<policy domain="coder" rights="none" pattern="PDF />

to

<policy domain="coder" rights="read|write" pattern="PDF />

**Comment by fehiepsi** [comment]
Confirmed that @irustandi solution works!

**Comment by AegeusZerium** [comment]
Thank you very much @irustandi, your solution worked.

**Comment by trylks** [comment]
The cause of the problem and its solution have been identified and the issue should be closed.

**Comment by usmandroid** [comment]
```
git clone https://github.com/mkrphys/ipython-tikzmagic.git
pip install -e ./ipython-tikzmagic
pip install pdflatex
sudo apt-get install texlive-latex-base
sudo apt-get install texlive-fonts-recommended; sudo apt-get install texlive-fonts-extra
sudo apt-get install texlive-latex-extra
sudo apt-get install pdf2svg
sudo apt install imagemagick
cd /etc/ImageMagick-6/
cd /etc/ImageMagick-6/
%
<!--  Next, I edited /etc/ImageMagick-6/policy.xml, changing the following
<policy domain="coder" rights="none" pattern="PDF />
to
<policy domain="coder" rights="read|write" pattern="PDF /> -->
%
sudo nano policy.xml
```
