### ISSUE TITLE
unable to generate svg

### ISSUE THREAD

**Issue by parthi2929** [mkrphys/ipython-tikzmagic#31]
Hi 

I am unable to generate SVG format. I have the working pdf2svg added to the system path and I also verified that pdf2svg is working in command prompt. Still I get below error. 

![image](https://user-images.githubusercontent.com/11896263/47661865-e4489a80-dbbf-11e8-93b2-e6641095b0bd.png)

Can you kindly check and help? I do not think there is any dependency issue. Perhaps, your sw is not generating the pdf itself? I could not see any pdf in my current or near folder where the notebook lies.

**Comment by AegeusZerium** [comment]
I have the exact same problem, no image was generated even though I installed all the necessary dependencies, if you found the solution to your problem please feel free to share as the developpers of tikz magic don't seem to be active or interested anymore.

**Comment by nquaz** [comment]
still interested and salty af for not looking at this issue before downloading everything

**Comment by trylks** [comment]
See [issue](https://github.com/mkrphys/ipython-tikzmagic/issues/18) #18 for a solution
