### ISSUE TITLE
No image generated; permission issue?

### ISSUE THREAD

**Issue by sbenthall** [mkrphys/ipython-tikzmagic#32]
Running the commands from the README gets me a "No image generated" warning

![image](https://user-images.githubusercontent.com/68752/74543518-80acc280-4f13-11ea-99b1-ad753142b71d.png)

In the command-line, I'm told that there's a permission issue accessing the generated pdf.

https://gist.github.com/sbenthall/41ca2c56bc951d2589ee80bbe5658f06

**Comment by mathsian** [comment]
I have this issue too. I had a dig and I think the problem is that without specifying a format the tool defaults to _creating_ a pdf but then trying to _open_ a png. Using

`%%tikz -f svg`

is a workaround for me.

**Comment by sbenthall** [comment]
Thank you; this workaround works for me.
(I also had to install `pdf2svg` for this to work.)

**Comment by dboeckenhoff** [comment]
This should be fixed if you dont want new users to be bounced right away. Thanks for the project :)
