### ISSUE TITLE
Error: No image generated.

### ISSUE THREAD

**Issue by gregnordin** [mkrphys/ipython-tikzmagic#5]
I have installed tikzmagic.py in ~/.ipython/extensions running on Mac OS X 10.10.4 with LiveTeX 2015 installed on my laptop. In an ipython notebook for both ipython 3.2 and ipython/jupyter 4.0 when I execute %load_ext tikzmagic and then %tikz \draw (0,0) rectangle (1,1); I do not get a rectangle as the output. Instead I get the message "No image generated." in stderr.

I am really puzzled as to what's going on. I have an older laptop running Mac OS X 10.9.4 with LiveTeX 2014 and it works fine there with ipython 3.2. Any ideas about how I can fix this? I love the package and use it with my university research group and would like to use it in course materials for some of the classes I teach.

**Comment by ghost** [comment]
I can reproduce this problem. Most likely you need to install ImageMagick and pdf2svg. Both are required to convert the LaTeX output to the various image formats. I forgot to write this in the README but just added it.

**Comment by gregnordin** [comment]
You are right--the problem was that ImageMagick and pdf2svg were not installed on my newer laptop. After installing them tikzmagic works great in my ipython notebooks. Thank you so much for the information!

**Comment by parthi2929** [comment]
How do we install via conda? 

```
conda install -c jakirkham pdf2svg
```

was not successful

**Comment by parthi2929** [comment]
And having binary of pdf2svg and adding that to path also did not help. I still get
```
pdf2svg terminated with signal -1
No image generated
```
